apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: volume-from-template
spec:
  tasks:
    - name: writer
      taskSpec:
        steps:
          - name: write
            image: ubuntu
            script: echo bar > $(workspaces.task-ws.path)/foo
        workspaces:
          - name: task-ws
      workspaces:
        - name: task-ws
          workspace: ws
    - name: reader
      runAfter:
        - writer
      taskSpec:
        steps:
          - name: read
            image: ubuntu
            script: cat $(workspaces.myws.path)/foo | grep bar
        workspaces:
          - name: git-source
      workspaces:
        - name: myws
          workspace: git-source
  workspaces:
    - name: git-source
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: run-with-template-
spec:
  pipelineRef:
    name: volume-from-template
  workspaces:
    - name: git-source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi